"""Brand-level grouping: merge naming variants of the same account."""
import re
from load import norm

# Parentheticals that mark genuinely separate accounts (kept in the key)
KEEP_PAREN = [r"mcdonald", r"mccafe"]

# regex on lowercased raw brand -> display name for the merged account
ALIASES = [
    (r"burgundy", "Axis Bank Burgundy (private banking)"),
    (r"^kotak mahindra (bank|group)", "Kotak Mahindra Bank"),
    (r"^mahindra suvs \(thar|^mahindra thar", "Mahindra Thar ROXX"),
    (r"^mahindra (\(ev|electric)", "Mahindra electric SUVs (BE 6, XEV 9e)"),
    (r"marriott (udaipur|resort & spa jim)", "Marriott Udaipur and Jim Corbett"),
    (r"^raffles, fairmont|^accor", "Accor India (Raffles, Fairmont, Sofitel)"),
    (r"^rambagh|^taj lands end", "Taj Hotels (IHCL)"),
    (r"^state bank of india|^sbi \(", "State Bank of India"),
    (r"^the oberoi hotels", "The Oberoi Group (EIH)"),
    (r"^k raheja", "K Raheja Corp"),
    (r"^bajaj allianz|^bajaj finserv", "Bajaj Finserv insurance (Bajaj Life, Bajaj General)"),
    (r"^club mahindra", "Club Mahindra (Club M)"),
    (r"^mccafe|mcdonald.*north", "McDonald's India (North & East)"),
    (r"mcdonald.*west", "McDonald's India (West & South)"),
    (r"^3m consumer", "3M Consumer Business"),
    (r"^aakash", "Aakash Educational Services"),
    (r"^arvind l", "Arvind Limited"),
    (r"^audi india", "Audi India"),
    (r"^bacardi", "Bacardi India"),
    (r"bgmi|battlegrounds", "BGMI (Krafton India)"),
    (r"^bhima", "Bhima Jewellers"),
    (r"^bajaj almond", "Bajaj Almond Drops"),
    (r"^casagrand", "Casagrand"),
    (r"^cera", "CERA Sanitaryware"),
    (r"^chalet hotels", "Chalet Hotels (Athiva)"),
    (r"^de beers|^forevermark", "De Beers Forevermark"),
    (r"^diageo india reserve", "Diageo India Reserve portfolio"),
    (r"^duolingo", "Duolingo"),
    (r"^estee lauder", "Estee Lauder India (Estee Lauder, MAC, Clinique)"),
    (r"^fujifilm", "Fujifilm India (instax, X Series)"),
    (r"^gulf oil|^gulf pride", "Gulf Oil Lubricants India"),
    (r"^haier", "Haier India"),
    (r"^hazoorilal", "Hazoorilal"),
    (r"^hero motocorp \(festive", "Hero MotoCorp"),
    (r"^indriya", "Indriya (Aditya Birla Jewellery)"),
    (r"^intel", "Intel India"),
    (r"interio", "Godrej Interio"),
    (r"^jack daniel", "Jack Daniel's"),
    (r"^jameson", "Jameson"),
    (r"^kisna", "KISNA"),
    (r"^kurl", "Kurlon"),
    (r"^l'occitane", "L'Occitane India"),
    (r"^l'oreal", "L'Oreal India"),
    (r"^lavie", "Lavie"),
    (r"^lenovo", "Lenovo India"),
    (r"^mccain", "McCain India"),
    (r"^mg windsor|^mg motor|jsw mg", "JSW MG Motor India"),
    (r"^myntra", "Myntra"),
    (r"^netflix", "Netflix India"),
    (r"^nykaa wanderlust", "Nykaa"),
    (r"^royal canin", "Royal Canin India"),
    (r"^samsung", "Samsung India"),
    (r"six fields|^devans|^godfather beer|^gianchand", "DeVANS (Godfather, Six Fields, GianChand)"),
    (r"^skoda", "Skoda Auto India"),
    (r"^spotify", "Spotify India"),
    (r"^standard chartered", "Standard Chartered India"),
    (r"^tvs ntorq", "TVS NTORQ"),
    (r"^tanishq \(rivaah|^rivaah", "Rivaah by Tanishq"),
    (r"^tata aig", "Tata AIG General Insurance"),
    (r"times of india", "The Times of India"),
    (r"kenneth cole|titan licensed", "Titan licensed watches (Kenneth Cole, Tommy Hilfiger)"),
    (r"^vivo", "vivo India"),
    (r"^realme", "realme"),
    (r"^wozoyo", "Wozoyo"),
    (r"^social( \(impresario\))?$", "SOCIAL (Impresario)"),
    (r"^flipkart( \(big billion days\))?$", "Flipkart"),
    (r"^coca-cola", "Coca-Cola India"),
    (r"^canon", "Canon India"),
    (r"^lotte", "Lotte India"),
    (r"^pernod ricard", "Pernod Ricard India"),
    (r"^mercedes", "Mercedes-Benz India"),
    (r"^asian paints( \(|$)", "Asian Paints"),
    (r"^dunkin", "Dunkin' India"),
    (r"^enamor", "Enamor"),
    (r"^pn gadgil", "PN Gadgil & Sons (PNGS)"),
    (r"^mahindra thar", "Mahindra Thar ROXX"),
    (r"^cult\.sport", "Cult.Sport"),
    (r"^runwal", "Runwal"),
    (r"^delhi duty free", "Delhi Duty Free"),
    (r"^mohey", "Mohey (Manyavar)"),
    (r"^adidas", "Adidas India"),
    (r"^fila", "FILA India"),
    (r"^lapis bard", "Lapis Bard"),
    (r"^orra$", "ORRA"),
    (r"^eveready$", "Eveready"),
    (r"^hdfc bank", "HDFC Bank"),
    (r"^taj hotels|^ihcl|^indian hotels", "Taj Hotels (IHCL)"),
    (r"^leela|^the leela palaces", "The Leela Palaces, Hotels and Resorts"),
    (r"^itc hotels", "ITC Hotels"),
    (r"^oberoi hotels|^the oberoi group|^eih", "The Oberoi Group (EIH)"),
    (r"^marriott (india|international)", "Marriott International India"),
    (r"^hyatt", "Hyatt India"),
    (r"^hilton", "Hilton India"),
    (r"^radisson", "Radisson Hotel Group India"),
    (r"^bmw", "BMW India"),
    (r"^jaguar|^jlr", "Jaguar Land Rover India"),
    (r"^volvo", "Volvo Cars India"),
    (r"^porsche", "Porsche India"),
    (r"^lexus", "Lexus India"),
    (r"^toyota", "Toyota Kirloskar Motor"),
    (r"^hyundai", "Hyundai Motor India"),
    (r"^kia", "Kia India"),
    (r"^royal enfield", "Royal Enfield"),
    (r"^tata motors (passenger|suv)|^tata\.ev|^tata ev", "Tata Motors Passenger Vehicles (incl. Tata.ev)"),
    (r"^godrej properties", "Godrej Properties"),
    (r"^dlf", "DLF"),
    (r"^lodha|^macrotech", "Lodha (Macrotech Developers)"),
    (r"^prestige", "Prestige Group"),
    (r"^sobha", "Sobha"),
    (r"^oberoi realty", "Oberoi Realty"),
    (r"^m3m", "M3M India"),
    (r"^icici bank", "ICICI Bank"),
    (r"^axis bank", "Axis Bank"),
    (r"^kotak mahindra bank", "Kotak Mahindra Bank"),
    (r"^american express|^amex", "American Express India"),
    (r"^360 ?one", "360 ONE Wealth"),
    (r"^air india$", "Air India"),
    (r"^indigo", "IndiGo"),
    (r"^akasa", "Akasa Air"),
]

def brand_key(raw):
    low = raw.lower().strip()
    for pat, disp in ALIASES:
        if re.search(pat, low):
            return norm(disp), disp
    if any(re.search(p, low) for p in KEEP_PAREN):
        return norm(raw), raw
    stripped = re.sub(r"\s*\([^)]*\)", "", raw).strip()
    return norm(stripped) or norm(raw), None
