"""Canonical agency names and groups, reflecting India structure as of Sep 2026."""
import re

# (regex on lowercased raw agency name, canonical name, group)
RULES = [
    (r"^unknown", "Unknown or in-house", "Unknown"),
    (r"22 ?feet|ddb tribal", "22feet Tribal Worldwide", "Omnicom"),
    (r"^80 ?db", "80dB Communications", "Independent"),
    (r"82\.5|grey|autumngrey", "Grey 82.5 (Ogilvy)", "WPP"),
    (r"^actimedia", "Actimedia PR", "Independent"),
    (r"^adglobal360", "AdGlobal360 (Hakuhodo)", "Hakuhodo"),
    (r"^adlift", "AdLift (Liqvd Asia)", "Independent"),
    (r"^liqvd", "Liqvd Asia", "Independent"),
    (r"^burson", "Burson India", "WPP"),
    (r"^contract", "Contract Advertising (VML)", "WPP"),
    (r"^ddb mudra|^mudra", "Mudra (ex DDB Mudra, BBDO Group)", "Omnicom"),
    (r"^bernbach", "Bernbach (Omnicom, VW unit)", "Omnicom"),
    (r"webchutney", "Dentsu Creative Webchutney", "Dentsu"),
    (r"isobar", "Dentsu Creative Isobar", "Dentsu"),
    (r"dentsu creative pr|perfect relations", "Dentsu Creative PR (ex Perfect Relations)", "Dentsu"),
    (r"dentsu sports", "Dentsu Sports & Entertainment", "Dentsu"),
    (r"taproot|watconsult|^dentsu", "Dentsu Creative India", "Dentsu"),
    (r"digitas|publicis digital experience", "Publicis Digital Experience (ex Digitas)", "Publicis"),
    (r"^enormous", "Enormous Brands", "Independent"),
    (r"^experience commerce", "Experience Commerce (Cheil)", "Cheil"),
    (r"^social beat", "Social Beat (Cheil)", "Cheil"),
    (r"^cheil x", "Cheil X", "Cheil"),
    (r"^cheil", "Cheil India", "Cheil"),
    (r"kinnect", "Kinnect", "Omnicom"),
    (r"ulka", "Ulka (BBDO Group)", "Omnicom"),
    (r"^fcb neo", "FCB Neo (absorbed into McCann)", "Omnicom"),
    (r"^fcb", "McCann India (ex FCB India)", "Omnicom"),
    (r"^gozoop", "Gozoop (now YAAP)", "Independent"),
    (r"^pmg india", "PMG India (Hakuhodo)", "Hakuhodo"),
    (r"^hakuhodo", "Hakuhodo India", "Hakuhodo"),
    (r"^havas media", "Havas Media India", "Havas"),
    (r"^havas creative|^havas worldwide", "Havas Creative India", "Havas"),
    (r"^pr pundit", "PR Pundit Havas Red", "Havas"),
    (r"^hiveminds", "HiveMinds (Madison)", "Independent"),
    (r"saatchi & saatchi propagate|^propagate", "Propagate India (Publicis)", "Publicis"),
    (r"l&k saatchi|^saatchi & saatchi", "Saatchi & Saatchi India", "Publicis"),
    (r"^scarecrow", "Scarecrow M&C Saatchi", "Independent"),
    (r"^leo", "Leo India", "Publicis"),
    (r"lintas live", "TBWA\\Lintas (ex Lintas Live)", "Omnicom"),
    (r"media arts lab", "TBWA\\Media Arts Lab India", "Omnicom"),
    (r"lintas|^tbwa", "TBWA\\Lintas", "Omnicom"),
    (r"^lodestar", "Lodestar UM (Omnicom Media)", "Omnicom"),
    (r"^initiative", "Initiative (Omnicom Media)", "Omnicom"),
    (r"^interactive avenues", "Interactive Avenues (Omnicom Media)", "Omnicom"),
    (r"^omd", "OMD India", "Omnicom"),
    (r"^omnicom media", "Omnicom Media India", "Omnicom"),
    (r"^omnicom", "Omnicom (unit not named)", "Omnicom"),
    (r"^madison loop|madison bmb", "Madison Loop (ex Madison BMB)", "Independent"),
    (r"^madison media|^madison world|^moms", "Madison Media", "Independent"),
    (r"^mirum", "Mirum India (VML)", "WPP"),
    (r"^ogilvy", "Ogilvy India", "WPP"),
    (r"^publicis india", "BBH India (ex Publicis India)", "Publicis"),
    (r"^bbh singapore", "BBH Singapore", "Publicis"),
    (r"^bbh", "BBH India", "Publicis"),
    (r"^publicis beehive", "Publicis Beehive", "Publicis"),
    (r"team spirit", "Team Spirit (Publicis)", "Publicis"),
    (r"^publicis media|^starcom|^zenith", "Publicis Media", "Publicis"),
    (r"^sw network|^sociowash", "SW Network (Sociowash)", "Independent"),
    (r"^toaster", "Toaster India", "Independent"),
    (r"^the glitch", "The Glitch (VML)", "WPP"),
    (r"^vml|^wunderman|^vmly&r|studio x \(vml\)", "VML India", "WPP"),
    (r"^bbdo", "BBDO India", "Omnicom"),
    (r"^mccann", "McCann India", "Omnicom"),
    (r"^ketchum", "Ketchum Sampark", "Omnicom"),
    (r"^weber shandwick", "Weber Shandwick India", "Omnicom"),
    (r"^wavemaker", "Wavemaker (WPP Media)", "WPP"),
    (r"^groupm|^wpp media|^essencemediacom", "WPP Media", "WPP"),
    (r"^hogarth", "Hogarth India", "WPP"),
    (r"^landor", "Landor India", "WPP"),
    (r"^wpp$", "WPP (unit not named)", "WPP"),
    (r"^msl", "MSL India", "Publicis"),
    (r"^a simple agency", "a Simple agency", "Independent"),
    (r"^popkorn", "popkorn (Value 360)", "Independent"),
    (r"^value ?360", "Value 360 Communications", "Independent"),
    (r"^chimp", "Chimp&z Inc", "Independent"),
    (r"^concept (pr|communications)", "Concept PR (Concept Communications)", "Independent"),
    (r"^innocean", "INNOCEAN India", "Other"),
    (r"^wondrlab", "Wondrlab", "Independent"),
    (r"^arena media", "Arena Media India (Havas)", "Havas"),
    (r"^accenture", "Accenture Song", "Other"),
]

GROUP_FIX = {
    "Omnicom (ex IPG)": "Omnicom", "Cheil SWA Group": "Cheil", "Cheil SWA (Samsung)": "Cheil",
    "LS Digital": "Independent", "YAAP (merger)": "Independent", "Liqvd Asia": "Independent",
    "Schbang Network": "Independent",
}

def canon_agency(name, group):
    low = name.lower().strip()
    for pat, cname, cgroup in RULES:
        if re.search(pat, low):
            return cname, cgroup
    return name, GROUP_FIX.get(group, group)
