// All site copy lives here. Edit this file, then run `node build.mjs`.
// House rules: sentence case, no em or en dashes, no exclamation marks, no emojis.

export const site = {
  name: 'Mask360',
  url: 'https://mask360.agency',
  title: 'Mask360, the luxury creative house of India and the Gulf',
  description: 'Mask360 is the luxury creative house of India and the Gulf. Strategy, content, experiences and the systems behind them, made in Mumbai and Dubai.',
  email: 'connect@mask360.agency',
  founderEmail: 'kaavish@mask360.agency',
  credentials: 'https://mask360.work',
  legal: 'Mask360 is a trading name of Mask Management, Mumbai.',
  cities: ['Mumbai', 'Delhi', 'Bangalore', 'Dubai', 'Abu Dhabi'],
  offices: [
    { city: 'Mumbai', lines: ['6th Floor, Platinum Prive', 'Upper Juhu, Mumbai 400053', 'India'] },
    { city: 'Dubai', lines: ['Dubai and Abu Dhabi', 'United Arab Emirates'] },
  ],
};

export const nav = [
  { label: 'Work', href: '/work/' },
  { label: 'Studio', href: '/#studio' },
  { label: 'Contact', href: '/contact/' },
];

export const home = {
  hero: {
    micro: 'Mumbai · Dubai',
    h1: 'The luxury creative house of India <em>and the Gulf.</em>',
    lede: 'Strategy, content, experiences and the systems behind them. Made in Mumbai and Dubai for brands that already have taste.',
    video: 'hero',
    videoMobile: 'hero-mobile',
    caption: 'Anantara Jewel Bagh, Jaipur. Shot and cut by Mask360 Studio.',
  },
  work: { micro: 'Selected work', h2: 'Shown large. <em>Explained briefly.</em>', link: 'All work' },
  pillars: {
    micro: 'What we do',
    h2: 'Three pillars. <em>One house.</em>',
    items: [
      { label: 'Content', title: 'Creative content marketing', text: 'Identity, design, packaging, content systems, social and creator distribution.', list: ['Brand identity and packaging', 'Content systems and calendars', 'Film, stills and design', 'Social and creator distribution'] },
      { label: 'Experiential', title: 'Experiences and launches', text: 'Private UHNI evenings, brand and product launches, retail weekends, festival and expo scale.', list: ['Private experiences', 'Launches and activations', 'Retail weekends and festivals', 'Spatial and 3D design direction'] },
      { label: 'Systems', title: 'Performance and AI systems', text: 'Media, measurement and the workflows around the tools. We build the system, then run it.', list: ['Paid media and search', 'CRM, tracking and reporting', 'GenAI content pipelines', 'Site, schema and bots'] },
    ],
  },
  process: {
    micro: 'How we work',
    h2: 'The argument first. <em>The format second.</em>',
    steps: [
      { n: '01', title: 'The argument', text: 'The behavioural case comes before anything is designed. Who buys, why they hesitate, what moves them.' },
      { n: '02', title: 'The direction', text: 'One idea, art directed hard and written down before the build, so every hand on it makes the same thing.' },
      { n: '03', title: 'The production', text: 'Mask360 Studio shoots, cuts, grades and renders in house. The team that pitched it makes it.' },
      { n: '04', title: 'The system', text: 'The work ships as a system: calendars, pipelines, tracking and the AI workflows that hold quality when volume goes up.' },
    ],
  },
  numbers: {
    micro: 'In numbers',
    items: [
      { n: '₹27 Cr', t: 'GMV driven by our retail activations' },
      { n: '500M+', t: 'Impressions across campaigns' },
      { n: '21,000+', t: 'Guests at a single retail weekend' },
      { n: '5', t: 'Cities across two markets' },
    ],
  },
  founder: {
    micro: 'The founder',
    quote: 'Taste does not scale. <em>Structure does.</em>',
    note: 'anybody can get one campaign right. behavioural science is how you get the next nine right without the same four people in the room. everything we have won in the gulf came out of a room: somebody met us, watched us handle something small, and handed us something bigger a year later. that is how we like to be hired.',
    name: 'Kaavish Ramchandani',
    role: 'Founder and Chief Alchemist',
    bio: 'Nine years on Dior, Ferrari, Ajio Luxe, Lollapalooza, Swisse, Anantara, L’Oréal and Dyson. He also runs a fractional CMO practice for founder-led brands.',
  },
  studio: {
    micro: 'Mask360 Studio',
    h2: 'Two days on location. <em>Six weeks of content.</em>',
    text: 'Films, reels, stills, UGC, design and AI-made content, produced in Mumbai and Dubai and sold as a monthly content system. Pre production to colour and sound, all in house.',
    video: 'zorae-ruler',
    caption: 'ZORÁE, Dubai. Studio film.',
  },
  clients: {
    micro: 'Houses we have worked with',
    list: ['Dior', 'Ferrari', 'L’Oréal Professionnel', 'Dyson', 'St. Regis', 'Anantara Hotels & Resorts', 'Lollapalooza India', 'Ajio Luxe', 'Chivas Regal', 'Swisse', 'ZORÁE', 'BookMyShow', 'Fire-Boltt', 'Istituto Marangoni', 'Warner Music India', 'Saregama Carvaan', 'Sonata', 'EliteFit', 'Dubai Dates Nutrition', 'Nexa', 'Airbnb', 'Lodha Luxury', 'La Mercie', 'Verona by SkyHigh', 'D’Monde Polo Club', 'Sarah & Sandeep', 'Amit Sadh'],
    sectors: 'Luxury retail, beauty and personal care, hospitality, real estate, health and wellness, jewellery, D2C.',
  },
  contact: {
    micro: 'Contact',
    h2: 'Start <em>in a room.</em>',
    text: 'Everything we have won came out of one. Write to us, or come and see the work in person in Mumbai or Dubai.',
  },
  footer: {
    end: 'Made in Mumbai and Dubai.',
  },
};

export const contactPage = {
  title: 'Contact Mask360',
  description: 'Write to Mask360 in Mumbai or Dubai. New business, press and studio enquiries.',
  h1: 'Start <em>in a room.</em>',
  lede: 'Tell us the brand, the market and what needs to move. We reply within two working days.',
  form: { action: 'https://formsubmit.co/connect@mask360.agency', subject: 'New enquiry from mask360.agency' },
};

// ---------- Cases ----------
// media refs are `slug/name` under public/assets/img, videos are names under public/assets/video.

export const cases = [
  {
    slug: 'anantara-jewel-bagh',
    client: 'Anantara Hotels & Resorts',
    short: 'Anantara Jewel Bagh, Jaipur',
    title: 'Two days. One palace. <em>Forty two deliverables.</em>',
    kicker: 'Hospitality content system',
    year: '2026',
    market: 'Jaipur, India',
    lede: 'A full production at Anantara Jewel Bagh, Jaipur, shot in two days and delivered inside a week. Stills, films, cut-downs, colour and sound, all in house.',
    body: [
      'The property makes you slow down, look twice and frame everything three times because you can. We ran the whole production ourselves: pre production, shot lists, direction on the ground, two days of shooting, and post delivered inside a week.',
      'No outsourced edit suite, no white labelled crew. The team that pitched it shot it. The team that shot it cut it.',
      'What we handed over was a content system. Higgsfield, Claude and our internal skills stack did the heavy lifting in post, which is how two days of shooting became six weeks of content without dropping quality anywhere.',
    ],
    facts: [['Scope', 'Pre production, direction, two day shoot, post, colour, sound, stills retouching'], ['Deliverables', '42'], ['Turnaround', 'Post inside a week'], ['Output', 'Six weeks of content']],
    hero: { img: 'anantara/pavilion-dusk', alt: 'A marble pavilion and palms at Anantara Jewel Bagh at dusk' },
    featured: { img: 'anantara/pavilion-dusk', alt: 'Marble pavilion and palms at dusk, Anantara Jewel Bagh, Jaipur', span: 8, ar: '16/10' },
    gallery: [
      { img: 'anantara/facade-night', alt: 'The palace facade lit at night', span: 8, ar: '16/10' },
      { img: 'anantara/chef', alt: 'A chef plating in the kitchen', span: 4, ar: '4/5' },
      { img: 'anantara/peacock-bar', alt: 'The peacock mosaic bar', span: 6, ar: '16/10' },
      { img: 'anantara/mosaic-hall', alt: 'Mosaic hall with a marble fountain', span: 6, ar: '16/10' },
      { video: 'hero', alt: 'AI assisted edit of the palace', span: 12, ar: '16/9', caption: 'Edit built with Higgsfield on our own footage.' },
      { img: 'anantara/blue-alcove', alt: 'Blue tiled alcove with a table for two', span: 4, ar: '4/5' },
      { img: 'anantara/table-service', alt: 'Table service in the dining room', span: 8, ar: '16/10' },
      { img: 'anantara/colonnade', alt: 'Colonnade with sculptures', span: 6, ar: '16/10' },
      { img: 'anantara/courtyard-dusk', alt: 'The courtyard pool at dusk', span: 6, ar: '16/10' },
      { img: 'anantara/wardrobe', alt: 'Butler preparing the wardrobe', span: 4, ar: '4/5' },
      { img: 'anantara/bedroom', alt: 'A suite bedroom', span: 4, ar: '4/5' },
      { img: 'anantara/gilded-lounge', alt: 'Gilded lounge ceiling', span: 4, ar: '4/5' },
      { img: 'anantara/dining-room', alt: 'The dining room being set', span: 6, ar: '16/10' },
      { img: 'anantara/indoor-pool', alt: 'The indoor pool', span: 6, ar: '16/10' },
      { img: 'anantara/garden-axis', alt: 'Garden axis with fountains', span: 12, ar: '21/9' },
    ],
  },
  {
    slug: 'zorae',
    client: 'ZORÁE',
    short: 'ZORÁE, Dubai',
    title: 'A house that <em>never repeats itself.</em>',
    kicker: 'Brand, content and agency of record',
    year: '2026',
    market: 'Dubai and the GCC',
    lede: 'ZORÁE is a fine jewellery house between the Netherlands and the UAE, built on monthly drops, lab-grown diamonds and member-only access. Mask360 is its Middle East agency of record.',
    body: [
      'We built the identity around restraint: a visual and verbal system structured around the house’s capsule philosophy, time bound and deliberately minimal. It holds across monthly releases without ever needing to announce itself.',
      'From there, the content infrastructure: campaign direction, AI-generated film, product visual systems and a Shopify build, aligned to a house that releases in monthly windows. Social, brand and content strategy, integrated PR and the launches themselves sit with us across the UAE, Saudi Arabia, Kuwait, Qatar, Bahrain and Oman.',
      'Creators carry access. Loyalty runs on status, early visibility and belonging.',
    ],
    facts: [['Role', 'Middle East agency of record'], ['Scope', 'Identity, social, content, PR, launches, website'], ['Cadence', 'Monthly drops'], ['Markets', 'UAE, Saudi Arabia, Kuwait, Qatar, Bahrain, Oman']],
    hero: { video: 'zorae-portrait', alt: 'A model in profile wearing ZORÁE earrings' },
    featured: { img: 'zorae/necklace-skin', alt: 'A ZORÁE diamond necklace on skin', span: 4, ar: '4/5' },
    gallery: [
      { img: 'zorae/earrings-water', alt: 'Earrings resting in water on stone', span: 4, ar: '4/5' },
      { img: 'zorae/chiaroscuro', alt: 'Black and white portrait with earrings', span: 4, ar: '4/5' },
      { img: 'zorae/choker-product', alt: 'Unbound Current choker on cream', span: 4, ar: '4/5' },
      { video: 'zorae-ruler', alt: 'A ring measured against a ruler', span: 8, ar: '16/9', caption: 'Studio film for the Unbound drop.' },
      { img: 'zorae/hand-face', alt: 'Hand on face, join the house', span: 4, ar: '4/5' },
      { img: 'zorae/organic-silhouettes', alt: 'Organic Silhouettes editorial', span: 4, ar: '4/5' },
      { img: 'zorae/pear-ring', alt: 'Pear cut ring on cream', span: 4, ar: '4/5' },
      { img: 'zorae/wet-hair', alt: 'Black and white portrait, wet hair, drop earrings', span: 4, ar: '4/5' },
      { img: 'zorae/ring-sand', alt: 'A ring set in white sand', span: 4, ar: '4/5' },
      { img: 'zorae/eyes-closed', alt: 'Portrait with eyes closed', span: 4, ar: '4/5' },
      { img: 'zorae/necklace-fabric', alt: 'Necklace on blue fabric', span: 4, ar: '4/5' },
      { img: 'zorae/bob', alt: 'Beauty portrait with a bob', span: 4, ar: '4/5' },
      { img: 'zorae/rings-colour', alt: 'Rings, hand on face', span: 4, ar: '4/5' },
      { img: 'zorae/earrings-product', alt: 'Unbound Eclipse earrings on cream', span: 4, ar: '4/5' },
    ],
  },
  {
    slug: 'ajio-luxe-weekend',
    client: 'Ajio Luxe with Chivas Regal',
    short: 'Ajio Luxe Wkend, Mumbai',
    title: 'Luxury Lifestyle Weekend became <em>Ajio Luxe Wkend.</em>',
    kicker: 'Experiential and 360 campaign',
    year: '2023',
    market: 'Jio Garden, Mumbai',
    lede: 'A luxury retail weekend rebranded and run as an experience: art, automobiles, beauty, collectibles, culinary, design, fashion, jewellery and watches under one roof.',
    body: [
      'We rebranded Luxury Lifestyle Weekend into Ajio Luxe Wkend and owned the full funnel: identity, campaign, on-ground experience, curators and collaborators, celebrity and creator outreach, print, outdoor, digital and PR.',
      'Brands on the floor ran from Ferrari and Aston Martin to Panerai, Bulgari and Omega. Chivas Regal hosted the conversations. Curation was led by Ashiesh Shah.',
      'Total media outreach crossed 500 million: 450 million on digital, 30 million outdoor, 20 million in print, 2.5 million on radio.',
    ],
    facts: [['Guests', '21,000 and more over three days'], ['Media outreach', '500M+'], ['Categories', 'Nine'], ['Dates', '3 to 5 February 2023']],
    hero: { img: 'ajio-luxe-weekend/mural', alt: 'A yellow sports car in front of the Wkend mural' },
    featured: { img: 'ajio-luxe-weekend/ferrari-canopy', alt: 'A Ferrari under the canopy at Ajio Luxe Wkend', span: 4, ar: '4/5' },
    gallery: [
      { img: 'ajio-luxe-weekend/ferrari-canopy', alt: 'A Ferrari under the canopy', span: 4, ar: '4/5' },
      { img: 'ajio-luxe-weekend/chivas-pavilion', alt: 'The Chivas Regal pavilion at night', span: 8, ar: '16/10' },
      { img: 'ajio-luxe-weekend/gallery', alt: 'The art gallery', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/maybach', alt: 'A Maybach on the lawn', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/pastries', alt: 'Pastries under glass', span: 4, ar: '16/10' },
      { img: 'ajio-luxe-weekend/coffee', alt: 'The coffee bar', span: 4, ar: '4/5' },
      { img: 'ajio-luxe-weekend/chocolate', alt: 'La Folie chocolate', span: 4, ar: '4/5' },
      { img: 'ajio-luxe-weekend/chivas-stage', alt: 'A conversation on the Chivas stage', span: 8, ar: '16/10' },
      { img: 'ajio-luxe-weekend/tea', alt: 'A tea setting', span: 4, ar: '4/5' },
      { img: 'ajio-luxe-weekend/lawn', alt: 'The lawn with installations', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/ferrari-rear', alt: 'Ferrari 296 GTB by the Wkend sign', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/llw', alt: 'Luxury Lifestyle Weekend, the former identity', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/wkend-chivas', alt: 'The Wkend identity with Chivas', span: 6, ar: '16/10' },
      { img: 'ajio-luxe-weekend/key-visual', alt: 'Eat, shop, play. The key visual', span: 12, ar: '16/10' },
    ],
  },
  {
    slug: 'lollapalooza-nexa',
    client: 'Lollapalooza India with Nexa',
    short: 'Nexa Platinum Lounge, Lollapalooza India',
    title: 'A platinum lounge for <em>530 guests.</em>',
    kicker: 'Experiential',
    year: '2023',
    market: 'Mahalaxmi Race Course, Mumbai',
    lede: 'End-to-end management of the Nexa Platinum Lounge at Lollapalooza India, across all four stages, with a sold-out ticket run and a private guest list.',
    body: [
      'We oversaw operations across all four stages and curated the Nexa Platinum Lounge, securing Nexa as premium partner and designing the VIP experience for 530 guests. Ticketing sold out, with 400 tickets allocated to YPO members and the rest held for A-list guests and creators.',
      'Behind it: bar logistics, luxury food and drink, private sections, valet and shuttle flows, dedicated entry lanes, raised viewing platforms with sightlines to the two main stages, and butler service on the platform.',
    ],
    facts: [['Guests', '530'], ['Tickets to YPO', '400'], ['Stages', 'Four'], ['Footfall', '45,000 a day']],
    hero: { img: 'lollapalooza/stage-render', alt: 'Render of the Nexa Platinum Lounge stage' },
    featured: { img: 'lollapalooza/stage-render', alt: 'The Nexa Platinum Lounge at Lollapalooza India', span: 4, ar: '4/5' },
    gallery: [
      { img: 'lollapalooza/stage-render-2', alt: 'Lounge render, second view', span: 6, ar: '16/10' },
      { img: 'lollapalooza/site-plan', alt: 'Site plan of the lounge', span: 6, ar: '16/10' },
      { img: 'lollapalooza/site-plan-2', alt: 'Site plan detail', span: 12, ar: '16/10' },
    ],
  },
  {
    slug: 'ef-athletic',
    client: 'EF Athletic by EliteFit',
    short: 'EF Athletic, UAE and India',
    title: 'Born in Mumbai, <em>shot in Dubai.</em>',
    kicker: 'Brand launch, campaign and web',
    year: '2026',
    market: 'UAE and India',
    lede: 'A new athleisure brand from the EliteFit wellness club, launched with a campaign shot in the UAE and an online store built to sell across both markets.',
    body: [
      'Padel courts, palms and the Gulf light. The campaign put the range on real people in real places, and the same system carried the lookbook, the store and the launch content.',
      'We built the identity, the campaign, the store and the content calendar, so the brand launched with a full wardrobe of assets.',
    ],
    facts: [['Scope', 'Identity, campaign, e-commerce build, launch content'], ['Shot', 'United Arab Emirates'], ['Markets', 'UAE and India']],
    hero: { img: 'ef-athletic/group-padel', alt: 'Four women on a padel court in EF Athletic' },
    featured: { img: 'ef-athletic/tennis-balls', alt: 'EF Athletic campaign on the court', span: 4, ar: '4/5' },
    gallery: [
      { img: 'ef-athletic/tennis-balls', alt: 'Seated on the court with tennis balls', span: 4, ar: '4/5' },
      { img: 'ef-athletic/jump', alt: 'Two athletes jumping', span: 4, ar: '4/5' },
      { img: 'ef-athletic/trio-doorway', alt: 'Three in a doorway', span: 4, ar: '4/5' },
      { img: 'ef-athletic/palms', alt: 'Brown activewear under palms', span: 4, ar: '4/5' },
      { img: 'ef-athletic/drinks', alt: 'Two women with drinks on the court', span: 4, ar: '4/5' },
      { img: 'ef-athletic/beach', alt: 'Walking on the beach', span: 4, ar: '4/5' },
      { img: 'ef-athletic/green-court', alt: 'Group on the green court', span: 4, ar: '4/5' },
      { img: 'ef-athletic/pink-drink', alt: 'Pink activewear, drink in hand', span: 4, ar: '4/5' },
      { img: 'ef-athletic/two-men', alt: 'Two men in blue and black', span: 4, ar: '4/5' },
    ],
  },
  {
    slug: 'st-regis-mumbai',
    client: 'The St. Regis Mumbai',
    short: 'The St. Regis Mumbai',
    title: 'The penthouse, <em>on film.</em>',
    kicker: 'Brand film',
    year: '2023',
    market: 'Mumbai',
    lede: 'A brand film for the St. Regis Mumbai penthouse, cut for the big screen and for the vertical one.',
    body: [
      'Arrival, butler, pool, skyline, dinner. The film follows a single evening through the penthouse, with a vertical edit built for social from the ground up.',
    ],
    facts: [['Formats', 'Landscape and vertical'], ['Length', '2 min 24 s'], ['Scope', 'Concept, shoot, edit, grade']],
    hero: { video: 'stregis', alt: 'The St. Regis Mumbai penthouse film' },
    featured: { img: 'stregis/stregis-skyline', alt: 'The St. Regis Mumbai penthouse at dusk', span: 6, ar: '16/10' },
    gallery: [
      { img: 'stregis/stregis-pool', alt: 'The pool', span: 4, ar: '16/10' },
      { img: 'stregis/stregis-skyline', alt: 'The skyline lounge', span: 4, ar: '16/10' },
      { img: 'stregis/stregis-dining', alt: 'Dinner in the penthouse', span: 4, ar: '16/10' },
    ],
  },
  {
    slug: 'dior-istituto-marangoni',
    client: 'Dior with Istituto Marangoni',
    short: 'Dior x Istituto Marangoni',
    title: 'Indian craft, <em>in conversation.</em>',
    kicker: 'Content and film',
    year: '2023',
    market: 'Mumbai',
    lede: 'A filmed conversation on Indian craft in the global fashion industry, produced for Istituto Marangoni with Dior, from set to final episode.',
    body: [
      'One stage, two chairs and a question worth an hour: where Indian craft sits in the global fashion industry. We produced the episode: set, multi-camera shoot, edit, grade and the platform versions.',
    ],
    facts: [['Format', 'Long-form episode'], ['Length', '15 minutes'], ['Scope', 'Set, shoot, edit, grade, cut-downs']],
    hero: { img: 'dior/frame-1', alt: 'Two speakers on the Istituto Marangoni stage' },
    featured: { img: 'dior/frame-0', alt: 'Indian craft in the global fashion industry, the episode', span: 6, ar: '16/10' },
    gallery: [
      { img: 'dior/frame-0', alt: 'The set', span: 6, ar: '16/9' },
      { img: 'dior/frame-2', alt: 'In conversation', span: 6, ar: '16/9' },
      { img: 'dior/frame-3', alt: 'The guest', span: 12, ar: '16/9' },
    ],
  },
  {
    slug: 'fire-boltt',
    client: 'Fire-Boltt',
    short: 'Fire-Boltt Fire Lens',
    title: 'Fire Lens, <em>launched in 3D.</em>',
    kicker: '360 campaign and launch film',
    year: '2025',
    market: 'India',
    lede: 'A 360 campaign for Fire-Boltt, with the launch film for Fire Lens smart glasses built in 3D and a celebrity campaign with Vicky Kaushal.',
    body: [
      'The launch film moves from product to person: glasses built and lit in 3D, then worn on real faces in real light. The campaign carried across social, digital and the Vicky Kaushal films.',
    ],
    facts: [['Scope', 'Campaign, 3D launch film, celebrity campaign'], ['Formats', 'Film and social cut-downs']],
    hero: { video: 'fireboltt', alt: 'Fire Lens launch film' },
    featured: { img: 'fireboltt/fireboltt-glasses', alt: 'Fire Lens smart glasses', span: 6, ar: '16/10' },
    gallery: [
      { img: 'fireboltt/fireboltt-glasses', alt: 'The glasses in 3D', span: 6, ar: '16/9' },
      { img: 'fireboltt/fireboltt-face', alt: 'Worn on a real face', span: 6, ar: '16/9' },
    ],
  },
  {
    slug: 'chivas-regal',
    client: 'Chivas Regal',
    short: 'Chivas Regal Ultis XX',
    title: 'Ultis XX, <em>rendered in the dark.</em>',
    kicker: 'CGI and social assets',
    year: '2026',
    market: 'India',
    lede: 'Cinematic social assets for the Chivas Regal premium range, built in CGI around the Ultis XX bottle.',
    body: [
      'Crest, cork, pour, bottle. A four by five film built entirely in CGI, so the light behaves the way the brand wants it to and the bottle never has a bad day.',
    ],
    facts: [['Format', '4 by 5 social film'], ['Build', 'Full CGI'], ['Range', 'Chivas Regal Ultis XX']],
    hero: { video: 'chivas-ultis', alt: 'Chivas Regal Ultis XX in CGI', portrait: true },
    featured: { img: 'chivas/chivas-bottle', alt: 'Chivas Regal Ultis XX', span: 4, ar: '4/5' },
    gallery: [
      { img: 'chivas/chivas-crest', alt: 'The crest', span: 6, ar: '4/5' },
      { img: 'chivas/chivas-bottle', alt: 'The bottle', span: 6, ar: '4/5' },
    ],
  },
];

// Home page selection and layout, in order.
export const featured = [
  ['anantara-jewel-bagh', 8, '16/10'],
  ['zorae', 4, '4/5'],
  ['ajio-luxe-weekend', 4, '4/5'],
  ['chivas-regal', 4, '4/5'],
  ['ef-athletic', 4, '4/5'],
  ['st-regis-mumbai', 6, '16/10'],
  ['dior-istituto-marangoni', 6, '16/10'],
];

export const otherWork = [
  'La Mercie, brand identity and packaging',
  'Verona by SkyHigh, luxury real estate brochure',
  'D’Monde Polo Club, identity',
  'Prana Yoga Studio, identity',
  'Skroman, product brochure',
  'Lodha Luxury, founder-led films',
  'Airbnb, Jump Into Vacation, 2023',
  'Amit Sadh, Motor Cycles Saved My Life, post production for seasons two and three',
  'BookMyShow, Tribe Vibe',
  'L’Oréal Professionnel Paris',
  'Dyson',
  'Swisse, UAE launch',
  'Warner Music India, Saregama Carvaan, Sonata',
];
